name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: rm -rf dist && npm run build

      - name: Create package.json in dist/cjs and dist/esm
        run: |
          echo '{"type": "commonjs"}' > dist/cjs/package.json
          echo '{"type": "module"}' > dist/esm/package.json

#      - name: Publish package on NPM 📦
#        run: npm publish
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}