name: New Update From Template

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update to'
        required: true
        default: '1.0.0'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Update From Template
        run: |
          git clone https://github.com/Thre4dripper/NodeTs-Express-Service-Based-Template template
          cp template/src-typescript/config/socketConfig.ts src/config/socketConfig.ts
          cp template/src-typescript/config/swaggerConfig.ts src/config/swaggerConfig.ts
          cp template/src-typescript/app/utils/MasterController.ts src/MasterController.ts
          cp template/src-typescript/app/utils/AsyncHandler.ts src/AsyncHandler.ts
          cp template/src-typescript/app/utils/RequestBuilder.ts src/RequestBuilder.ts
          cp template/src-typescript/app/utils/ResponseBuilder.ts src/ResponseBuilder.ts
          rm -rf template

      - name: Push changes
        run: |
          git config --global user.name 'Update Bot'
          git config --global user.email 'updatebot@gmail.com'
          git add .
          git commit -m "Updated from template"
          git push